# Website settings
baseurl: "/"
url: "http://www.terraformupandrunning.com"
thumbnail_path: "terraform-up-and-running-cover-medium.png"

# About settings
name: "Terraform: Up & Running"
description: "This book is the fastest way to get up and running with Terraform, an open source tool that allows you to manage your infrastructure as code across a variety of cloud providers."
website_repo_url: "https://github.com/brikis98/terraform-up-and-running"
feedback_email: "jim@ybrikman.com"

# Jekyll build settings
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
